name: Continuous Delivery

on:
  release:
    types: [published]

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          version-type: "strict"
          version-file: ".tool-versions"
          install-hex: true
          install-rebar: true

      - name: Publish package
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: |
          mix deps.get
          mix hex.publish --yes
